name: disasters-test-main
channels:
  - conda-forge
dependencies:
  - asf_search
  - beautifulsoup4
  - boto3
  - earthaccess
  - gdal
  - geopandas
  - jupyterlab
  - leafmap
  - lxml
  - matplotlib
  - numpy
  - opera-utils
  - pip
  - pygmt
  - rasterio
  - rioxarray
  - tabulate
  - xarray
  - zarr==3.1.3
  - pip:
      - git+https://github.com/OPERA-Cal-Val/next_pass.git@main
