name: disasters
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal=3.12
  - libgdal=3.12
  - numpy<2.0
  - asf_search
  - beautifulsoup4
  - boto3
  - earthaccess
  - geopandas
  - jupyterlab
  - leafmap
  - lxml
  - matplotlib
  - opera-utils=0.25.3
  - pip
  - pygmt
  - rasterio
  - rioxarray
  - tabulate
  - xarray
  - zarr
  - openpyxl 
  
  - pip:
      - numpy<2.0
      - git+https://github.com/OPERA-Cal-Val/next_pass.git@main